### ISSUE TITLE
commenting a block of code can break

### ISSUE THREAD

**Issue by joelanman** [adamchainz/SublimeHTMLMustache#10]
firstly, thanks for your work

If I comment out a line like this:

```
<h4>Hello {{name}}</h4>
```

I get this:

```
{{! <h4>Hello {{name}}</h4> }}
```

Which doesn't work. Is it possible for me to change the comment syntax to html? ()

**Comment by adamchainz** [comment]
Hey, the `{{! comment }}` syntax is [part of mustache](https://mustache.github.io/mustache.5.html), and that's why the language definition does this by default. Template language level comments are useful since they don't get rendered to the client, whilst the HTML comments do.

If you want to only use HTML comments, because e.g. your mustache library doesn't support `{{!`, you'd probably be best either forking this package to remove the comments stuff (not hard, just delete the relevant lines from the `tmLanguage` and `tmPreferences` files), or using a Sublime Text macro bound to a shortcut to create your HTML comments. I don't think there's anything I can do in the main repo to allow them to be optional I'm afraid!

**Comment by joelanman** [comment]
thanks for the reply - I understand it's how moustache does comments, but unfortunately it breaks any code that actually has a moustache tag in it - the comment ends at the first `}}` not the second. So in real world usage thats not very helpful. Cheers for the workaround suggestions, I'll try them

**Comment by adamchainz** [comment]
Yes it's annoying that mustache comment termination is indistinguishable from variables, it's a bit too simple in that respect. You might be able to make a 'comment' macro that 'escapes' `}}` into `}\}`, and an 'uncomment' macro that unescapes them. HTML comments with `{{ varname }}` in will still get mustache to render the variable which will potentially be broken in your codebase anyway.
